### ISSUE TITLE
GITHUB_TOKEN

### ISSUE THREAD

**Issue by danielbayley** [ahmadnassri/action-dependabot-auto-merge#33]
Similar to #11, #21, #1…

@ahmadnassri is there a reason we can't just use `github-token: ${{ secrets.GITHUB_TOKEN }}` directly? (Obviously `GITHUB_TOKEN` has the correct scopes in my case.)

**Comment by emi190396** [comment]
:+1:

**Comment by ahmadnassri** [comment]
since this action uses `@dependabot` commands _(e.g. `@dependabot merge`)_ the actual merging logic lives within dependabot itself, and that requires a *user token* not the Actions repo token ... this is a limitation by dependabot itself, not this action.

###### dependabot commands
![image](https://user-images.githubusercontent.com/183195/96152498-9d522d80-0eda-11eb-89bb-cffaa76a4174.png)

###### dependabot error message
![image](https://user-images.githubusercontent.com/183195/96152628-bfe44680-0eda-11eb-992d-c278aaf046b8.png)

**Comment by ahmadnassri** [comment]
perhaps this is something to bring up to GitHub to add to dependabot ... would be nice to never have to put any token in the action yaml for sure
