### ISSUE TITLE
"EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by peterbe** [ahmadnassri/action-dependabot-auto-merge#44]
See https://github.com/mdn/content/pull/216/checks?check_run_id=1555249799

```
Run ahmadnassri/action-dependabot-auto-merge@v2.2.4
/usr/bin/docker run --name ghcrioahmadnassriactiondependabotautomergev2_fb18bb --label 179394 --workdir /github/workspace --rm -e INPUT_GITHUB-TOKEN -e INPUT_COMMAND -e INPUT_APPROVE -e INPUT_TARGET -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/content/content":"/github/workspace" ghcr.io/ahmadnassri/action-dependabot-auto-merge:v2
Error: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:611:3)
    at tryReadSync (node:fs:385:20)
    at Object.readFileSync (node:fs:422:19)
    at default (file:///action/lib/config.js:18:27)
    at default (file:///action/lib/index.js:23:13)
    at file:///action/index.js:52:7
    at ModuleJob.run (node:internal/modules/esm/module_job:152:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

The config is here: https://github.com/mdn/content/blob/main/.github/workflows/auto-merge.yml

**Comment by peterbe** [comment]
Seems bumping from v2.2.4 to v2.3 resolved it.

**Comment by peterbe** [comment]
No, it's still happening :(
See https://github.com/mdn/yari/pull/2176/checks?check_run_id=1568487833
Here's the PR https://github.com/mdn/yari/pull/2176

**Comment by peterbe** [comment]
@ahmadnassri I'm not sure if you get notifications, if you're not already mentioned, when an issue gets re-opened.

**Comment by ahmadnassri** [comment]
I do get the notification on reopen (and every comment)

the first time this happened, I was going to respond and say the issue seems odd, since [line 18 is asking to read a specific file path](https://github.com/ahmadnassri/action-dependabot-auto-merge/blob/992a700111b9aca763258775403d182a643a6387/action/lib/config.js#L18) but then you updated to v2.3.0 and that seems to resolve it ... still weird tho...

this time, it's a different repo that's still using v2.4.4

the change between the two is related to the config file path, but I don't see why the latter version works... (especially that 2.4.4 had been working all along!)

in any case, start with updating this repo to also use 2.3?

**Comment by peterbe** [comment]
Oh this is so confusing :)
See https://github.com/mdn/yari/pull/2146/checks?check_run_id=1555168017
The reason:
```
Warning: failed to parse title: no recognizable versions
```
...even though the PR title (thanks Dependabot) is:
```
build(deps): bump ahmadnassri/action-dependabot-auto-merge from v2.2.4 to v2.3
```

I'll merge it manually for now and see if that makes everything hunky dory.

**Comment by peterbe** [comment]
Wohoo! [Works now](https://github.com/mdn/yari/pull/2176#issuecomment-747667547)
v2.3 is da bomb. 
Close again?

**Comment by ahmadnassri** [comment]
ah the non smever thing again ... I still have not gotten a response from dependabot on that: https://github.com/dependabot/dependabot-core/issues/2659

I think I'll just implement a method to translate `x.y` to `x.y.z` since dependabot team doesn't seem to want to respond ...

as for the original issue described here ... seemed resolved with the latest version so will close ... let me know if occurs again
